In [32]:
import numpy as np
import pandas as pd 
from math import exp,log
data=pd.read_csv("x_y_train.csv")
x_test=pd.read_csv("x_test.csv")
x_train=data.iloc[:,0:(data.shape)[1]-1]
y_train=data.iloc[:,(data.shape)[1]-1]
x_train.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.0,1,0,228414,26.000,NaN,S
1,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.050,NaN,S
2,2,"Morley, Mr. Henry Samuel (""Mr Henry Marshall"")",male,39.0,0,0,250655,26.000,NaN,S
3,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,349909,21.075,NaN,S
4,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S

In [33]:
x_train.drop(['Name','Fare','Ticket','Cabin'],axis=1,inplace=True)
x_test.drop(['Name','Fare','Ticket','Cabin'],axis=1,inplace=True)
print(x_train.shape)
print(x_test.shape)

(668, 6)
(223, 6)

In [34]:
def f(s):
    if s=='C':
        return 0
    elif s=='Q':
        return 1
    elif s=='S':
        return 2
def k(s):
    if s=='male':
        return 0
    elif s=='female':
        return 1
x_train['embarked']=x_train['Embarked'].apply(f)
x_train['sex']=x_train['Sex'].apply(k)
x_test['embarked']=x_test['Embarked'].apply(f)
x_test['sex']=x_test['Sex'].apply(k)
print(x_train.shape)
print(x_test.shape)

(668, 8)
(223, 8)

In [35]:
x_train.drop(['Embarked','Sex'],axis=1,inplace=True)
x_test.drop(['Embarked','Sex'],axis=1,inplace=True)

In [36]:
print(x_train.head())
print(x_test.head())

   Pclass   Age  SibSp  Parch  embarked  sex
0       2  29.0      1      0       2.0    1
1       3   NaN      0      0       2.0    0
2       2  39.0      0      0       2.0    0
3       3  29.0      0      4       2.0    1
4       3  25.0      0      0       2.0    0
   Pclass   Age  SibSp  Parch  embarked  sex
0       2   8.0      1      1       2.0    0
1       1  49.0      0      0       2.0    1
2       3   NaN      0      0       1.0    0
3       2  24.0      2      1       2.0    1
4       1  36.0      0      0       2.0    0

In [37]:
x_train=np.array(x_train)
y_train=np.array(y_train)
data=np.concatenate((x_train,y_train.reshape(-1,1)),axis=1)
data=pd.DataFrame(data)
data.columns=['Pclass','Age','SibSp','Parch','embarked','Sex','Survived']
data

     Pclass    Age  SibSp  Parch  embarked  Sex  Survived
0       2.0  29.00    1.0    0.0       2.0  1.0       1.0
1       3.0    NaN    0.0    0.0       2.0  0.0       0.0
2       2.0  39.00    0.0    0.0       2.0  0.0       0.0
3       3.0  29.00    0.0    4.0       2.0  1.0       0.0
4       3.0  25.00    0.0    0.0       2.0  0.0       0.0
5       3.0  34.50    0.0    0.0       0.0  0.0       0.0
6       1.0  35.00    1.0    0.0       2.0  1.0       1.0
7       3.0  23.00    0.0    0.0       2.0  0.0       0.0
8       2.0    NaN    0.0    0.0       2.0  0.0       1.0
9       3.0  50.00    0.0    0.0       2.0  0.0       0.0
10      3.0  23.00    0.0    0.0       2.0  1.0       1.0
11      3.0    NaN    0.0    0.0       0.0  0.0       0.0
12      2.0  36.00    0.0    0.0       2.0  0.0       0.0
13      3.0    NaN    1.0    0.0       1.0  0.0       0.0
14      3.0    NaN    0.0    0.0       1.0  1.0       1.0
15      3.0  28.00    2.0    0.0       2.0  0.0       0.0
16      3.0  32.00    0.0    0.0       2.0  0.0       1.0
17      3.0  42.00    0.0    0.0       2.0  0.0       0.0
18      1.0  38.00    0.0    1.0       2.0  0.0       0.0
19      3.0    NaN    0.0    0.0       1.0  1.0       1.0
20      1.0  38.00    0.0    0.0       2.0  0.0       0.0
21      3.0    NaN    0.0    2.0       0.0  1.0       0.0
22      2.0  40.00    0.0    0.0       2.0  1.0       1.0
23      3.0  24.50    0.0    0.0       2.0  0.0       0.0
24      3.0    NaN    0.0    0.0       0.0  1.0       1.0
25      3.0    NaN    8.0    2.0       2.0  1.0       0.0
26      1.0  39.00    0.0    0.0       2.0  0.0       0.0
27      1.0  22.00    0.0    0.0       0.0  0.0       0.0
28      3.0  16.00    0.0    0.0       2.0  0.0       0.0
29      2.0  30.00    0.0    0.0       2.0  0.0       0.0
..      ...    ...    ...    ...       ...  ...       ...
638     3.0  24.00    2.0    0.0       2.0  0.0       0.0
639     2.0  22.00    1.0    2.0       0.0  1.0       1.0
640     3.0    NaN    3.0    1.0       2.0  1.0       0.0
641     3.0  32.00    0.0    0.0       2.0  0.0       1.0
642     1.0  42.00    0.0    0.0       2.0  0.0       1.0
643     3.0  17.00    0.0    0.0       2.0  0.0       0.0
644     1.0    NaN    0.0    0.0       2.0  0.0       0.0
645     2.0   0.83    1.0    1.0       2.0  0.0       1.0
646     3.0   9.00    2.0    2.0       2.0  1.0       0.0
647     1.0  58.00    0.0    0.0       0.0  0.0       0.0
648     2.0  28.00    0.0    1.0       2.0  0.0       0.0
649     3.0  26.00    0.0    0.0       2.0  0.0       0.0
650     3.0  47.00    0.0    0.0       2.0  0.0       0.0
651     3.0    NaN    1.0    0.0       2.0  0.0       0.0
652     2.0  33.00    1.0    2.0       2.0  1.0       1.0
653     3.0  47.00    1.0    0.0       2.0  1.0       0.0
654     3.0    NaN    0.0    0.0       2.0  0.0       0.0
655     1.0  42.00    1.0    0.0       2.0  0.0       1.0
656     3.0  36.00    0.0    0.0       2.0  0.0       0.0
657     3.0  38.00    0.0    0.0       2.0  0.0       0.0
658     3.0  38.00    1.0    5.0       2.0  1.0       1.0
659     3.0    NaN    0.0    0.0       1.0  0.0       0.0
660     2.0   1.00    2.0    1.0       2.0  0.0       1.0
661     1.0    NaN    1.0    0.0       0.0  1.0       1.0
662     1.0  47.00    0.0    0.0       2.0  0.0       0.0
663     2.0  17.00    0.0    0.0       2.0  1.0       1.0
664     3.0    NaN    0.0    0.0       1.0  0.0       0.0
665     3.0  32.00    0.0    0.0       2.0  0.0       1.0
666     3.0  22.00    0.0    0.0       2.0  1.0       0.0
667     3.0    NaN    1.0    0.0       1.0  1.0       1.0

[668 rows x 7 columns]

In [38]:
data.head()

   Pclass   Age  SibSp  Parch  embarked  Sex  Survived
0     2.0  29.0    1.0    0.0       2.0  1.0       1.0
1     3.0   NaN    0.0    0.0       2.0  0.0       0.0
2     2.0  39.0    0.0    0.0       2.0  0.0       0.0
3     3.0  29.0    0.0    4.0       2.0  1.0       0.0
4     3.0  25.0    0.0    0.0       2.0  0.0       0.0

In [39]:
means=data[data['Survived']==1]['Age'].mean()
means

28.138157894736842

In [40]:
meann=data[data['Survived']==0]['Age'].mean()
meann

30.857142857142858

In [41]:
data["age1"]=np.where(pd.isnull(data.Age) & (data["Survived"]==0),meann,data["Age"])
data.head()

   Pclass   Age  SibSp  Parch  embarked  Sex  Survived       age1
0     2.0  29.0    1.0    0.0       2.0  1.0       1.0  29.000000
1     3.0   NaN    0.0    0.0       2.0  0.0       0.0  30.857143
2     2.0  39.0    0.0    0.0       2.0  0.0       0.0  39.000000
3     3.0  29.0    0.0    4.0       2.0  1.0       0.0  29.000000
4     3.0  25.0    0.0    0.0       2.0  0.0       0.0  25.000000

In [42]:
data['age1'].fillna(means,inplace=True)

In [43]:
data.drop(['Age'],axis=1,inplace=True)

In [44]:
data.dropna(inplace=True)

In [45]:

data=np.array(data)
data=pd.DataFrame(data)
data.columns=[0,1,2,3,4,6,5]
data.sort_index(axis=1,inplace=True)
data

       0    1    2    3    4          5    6
0    2.0  1.0  0.0  2.0  1.0  29.000000  1.0
1    3.0  0.0  0.0  2.0  0.0  30.857143  0.0
2    2.0  0.0  0.0  2.0  0.0  39.000000  0.0
3    3.0  0.0  4.0  2.0  1.0  29.000000  0.0
4    3.0  0.0  0.0  2.0  0.0  25.000000  0.0
5    3.0  0.0  0.0  0.0  0.0  34.500000  0.0
6    1.0  1.0  0.0  2.0  1.0  35.000000  1.0
7    3.0  0.0  0.0  2.0  0.0  23.000000  0.0
8    2.0  0.0  0.0  2.0  0.0  28.138158  1.0
9    3.0  0.0  0.0  2.0  0.0  50.000000  0.0
10   3.0  0.0  0.0  2.0  1.0  23.000000  1.0
11   3.0  0.0  0.0  0.0  0.0  30.857143  0.0
12   2.0  0.0  0.0  2.0  0.0  36.000000  0.0
13   3.0  1.0  0.0  1.0  0.0  30.857143  0.0
14   3.0  0.0  0.0  1.0  1.0  28.138158  1.0
15   3.0  2.0  0.0  2.0  0.0  28.000000  0.0
16   3.0  0.0  0.0  2.0  0.0  32.000000  1.0
17   3.0  0.0  0.0  2.0  0.0  42.000000  0.0
18   1.0  0.0  1.0  2.0  0.0  38.000000  0.0
19   3.0  0.0  0.0  1.0  1.0  28.138158  1.0
20   1.0  0.0  0.0  2.0  0.0  38.000000  0.0
21   3.0  0.0  2.0  0.0  1.0  30.857143  0.0
22   2.0  0.0  0.0  2.0  1.0  40.000000  1.0
23   3.0  0.0  0.0  2.0  0.0  24.500000  0.0
24   3.0  0.0  0.0  0.0  1.0  28.138158  1.0
25   3.0  8.0  2.0  2.0  1.0  30.857143  0.0
26   1.0  0.0  0.0  2.0  0.0  39.000000  0.0
27   1.0  0.0  0.0  0.0  0.0  22.000000  0.0
28   3.0  0.0  0.0  2.0  0.0  16.000000  0.0
29   2.0  0.0  0.0  2.0  0.0  30.000000  0.0
..   ...  ...  ...  ...  ...        ...  ...
637  3.0  2.0  0.0  2.0  0.0  24.000000  0.0
638  2.0  1.0  2.0  0.0  1.0  22.000000  1.0
639  3.0  3.0  1.0  2.0  1.0  30.857143  0.0
640  3.0  0.0  0.0  2.0  0.0  32.000000  1.0
641  1.0  0.0  0.0  2.0  0.0  42.000000  1.0
642  3.0  0.0  0.0  2.0  0.0  17.000000  0.0
643  1.0  0.0  0.0  2.0  0.0  30.857143  0.0
644  2.0  1.0  1.0  2.0  0.0   0.830000  1.0
645  3.0  2.0  2.0  2.0  1.0   9.000000  0.0
646  1.0  0.0  0.0  0.0  0.0  58.000000  0.0
647  2.0  0.0  1.0  2.0  0.0  28.000000  0.0
648  3.0  0.0  0.0  2.0  0.0  26.000000  0.0
649  3.0  0.0  0.0  2.0  0.0  47.000000  0.0
650  3.0  1.0  0.0  2.0  0.0  30.857143  0.0
651  2.0  1.0  2.0  2.0  1.0  33.000000  1.0
652  3.0  1.0  0.0  2.0  1.0  47.000000  0.0
653  3.0  0.0  0.0  2.0  0.0  30.857143  0.0
654  1.0  1.0  0.0  2.0  0.0  42.000000  1.0
655  3.0  0.0  0.0  2.0  0.0  36.000000  0.0
656  3.0  0.0  0.0  2.0  0.0  38.000000  0.0
657  3.0  1.0  5.0  2.0  1.0  38.000000  1.0
658  3.0  0.0  0.0  1.0  0.0  30.857143  0.0
659  2.0  2.0  1.0  2.0  0.0   1.000000  1.0
660  1.0  1.0  0.0  0.0  1.0  28.138158  1.0
661  1.0  0.0  0.0  2.0  0.0  47.000000  0.0
662  2.0  0.0  0.0  2.0  1.0  17.000000  1.0
663  3.0  0.0  0.0  1.0  0.0  30.857143  0.0
664  3.0  0.0  0.0  2.0  0.0  32.000000  1.0
665  3.0  0.0  0.0  2.0  1.0  22.000000  0.0
666  3.0  1.0  0.0  1.0  1.0  28.138158  1.0

[667 rows x 7 columns]

In [46]:
data.columns=['Pclass','Sibsp','Parch','embarked','sex','age','Survived']
data.drop(['Parch','embarked'],axis=1,inplace=True)
data

     Pclass  Sibsp  sex        age  Survived
0       2.0    1.0  1.0  29.000000       1.0
1       3.0    0.0  0.0  30.857143       0.0
2       2.0    0.0  0.0  39.000000       0.0
3       3.0    0.0  1.0  29.000000       0.0
4       3.0    0.0  0.0  25.000000       0.0
5       3.0    0.0  0.0  34.500000       0.0
6       1.0    1.0  1.0  35.000000       1.0
7       3.0    0.0  0.0  23.000000       0.0
8       2.0    0.0  0.0  28.138158       1.0
9       3.0    0.0  0.0  50.000000       0.0
10      3.0    0.0  1.0  23.000000       1.0
11      3.0    0.0  0.0  30.857143       0.0
12      2.0    0.0  0.0  36.000000       0.0
13      3.0    1.0  0.0  30.857143       0.0
14      3.0    0.0  1.0  28.138158       1.0
15      3.0    2.0  0.0  28.000000       0.0
16      3.0    0.0  0.0  32.000000       1.0
17      3.0    0.0  0.0  42.000000       0.0
18      1.0    0.0  0.0  38.000000       0.0
19      3.0    0.0  1.0  28.138158       1.0
20      1.0    0.0  0.0  38.000000       0.0
21      3.0    0.0  1.0  30.857143       0.0
22      2.0    0.0  1.0  40.000000       1.0
23      3.0    0.0  0.0  24.500000       0.0
24      3.0    0.0  1.0  28.138158       1.0
25      3.0    8.0  1.0  30.857143       0.0
26      1.0    0.0  0.0  39.000000       0.0
27      1.0    0.0  0.0  22.000000       0.0
28      3.0    0.0  0.0  16.000000       0.0
29      2.0    0.0  0.0  30.000000       0.0
..      ...    ...  ...        ...       ...
637     3.0    2.0  0.0  24.000000       0.0
638     2.0    1.0  1.0  22.000000       1.0
639     3.0    3.0  1.0  30.857143       0.0
640     3.0    0.0  0.0  32.000000       1.0
641     1.0    0.0  0.0  42.000000       1.0
642     3.0    0.0  0.0  17.000000       0.0
643     1.0    0.0  0.0  30.857143       0.0
644     2.0    1.0  0.0   0.830000       1.0
645     3.0    2.0  1.0   9.000000       0.0
646     1.0    0.0  0.0  58.000000       0.0
647     2.0    0.0  0.0  28.000000       0.0
648     3.0    0.0  0.0  26.000000       0.0
649     3.0    0.0  0.0  47.000000       0.0
650     3.0    1.0  0.0  30.857143       0.0
651     2.0    1.0  1.0  33.000000       1.0
652     3.0    1.0  1.0  47.000000       0.0
653     3.0    0.0  0.0  30.857143       0.0
654     1.0    1.0  0.0  42.000000       1.0
655     3.0    0.0  0.0  36.000000       0.0
656     3.0    0.0  0.0  38.000000       0.0
657     3.0    1.0  1.0  38.000000       1.0
658     3.0    0.0  0.0  30.857143       0.0
659     2.0    2.0  0.0   1.000000       1.0
660     1.0    1.0  1.0  28.138158       1.0
661     1.0    0.0  0.0  47.000000       0.0
662     2.0    0.0  1.0  17.000000       1.0
663     3.0    0.0  0.0  30.857143       0.0
664     3.0    0.0  0.0  32.000000       1.0
665     3.0    0.0  1.0  22.000000       0.0
666     3.0    1.0  1.0  28.138158       1.0

[667 rows x 5 columns]

In [47]:
mean=x_test['Age'].mean()
mean

29.694775280898877

In [48]:
x_test['age']=np.where(pd.isnull(x_test.Age),mean,x_test['Age'])
x_test.drop(['Age','Parch','embarked'],axis=1,inplace=True)
x_test

     Pclass  SibSp  sex        age
0         2      1    0   8.000000
1         1      0    1  49.000000
2         3      0    0  29.694775
3         2      2    1  24.000000
4         1      0    0  36.000000
5         1      0    0  71.000000
6         3      0    0  16.000000
7         3      0    0  29.694775
8         3      0    1  18.000000
9         3      0    0  29.694775
10        1      1    1  63.000000
11        3      0    0  29.694775
12        1      0    1  24.000000
13        3      0    1  23.000000
14        1      0    0  71.000000
15        2      1    0  21.000000
16        3      0    0  21.000000
17        3      1    0   4.000000
18        3      0    0  22.000000
19        3      0    1  18.000000
20        3      1    1  29.694775
21        3      0    0  32.000000
22        1      0    1  58.000000
23        2      1    1  24.000000
24        3      0    0  29.694775
25        1      0    0  29.694775
26        2      0    0  28.000000
27        1      1    0  42.000000
28        3      2    1   0.750000
29        2      0    1  50.000000
..      ...    ...  ...        ...
193       3      0    0  29.694775
194       3      0    0  38.000000
195       3      0    1  26.000000
196       1      0    1  16.000000
197       3      0    1  37.000000
198       2      1    1  28.000000
199       1      0    1  33.000000
200       3      0    0  29.694775
201       1      0    0  32.000000
202       3      0    0  22.000000
203       1      0    0  47.000000
204       3      0    0  29.694775
205       3      1    0  29.694775
206       3      0    0  32.000000
207       3      0    0  26.000000
208       1      0    1  62.000000
209       3      3    1   9.000000
210       3      2    0  29.694775
211       3      0    1  22.000000
212       2      0    0  25.000000
213       1      0    0  55.000000
214       3      0    1  14.000000
215       2      0    1  29.694775
216       3      0    0  21.000000
217       3      0    0  29.694775
218       3      1    0  20.000000
219       1      0    0  45.000000
220       1      1    1  17.000000
221       3      0    0  43.000000
222       2      0    0  36.500000

[223 rows x 4 columns]

In [49]:
data=np.array(data)
x_test=np.array(x_test)

In [50]:
x_train=data[:,0:(data.shape)[1]-1]
y_train=data[:,(data.shape)[1]-1]

In [51]:
from sklearn import preprocessing
scaler=preprocessing.StandardScaler()
scaler.fit(x_train)
scaler.transform(x_train)
scaler.transform(x_test)

array([[-3.59407249e-01,  4.35839637e-01, -7.49707203e-01,
        -1.70420669e+00],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
         1.50833981e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-3.59407249e-01,  1.36165186e+00,  1.33385406e+00,
        -4.50530011e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         4.89727501e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         3.23214524e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -1.07736835e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -9.20658767e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-1.56405366e+00,  4.35839637e-01,  1.33385406e+00,
         2.60530690e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
        -4.50530011e-01],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -5.28884803e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         3.23214524e+00],
       [-3.59407249e-01,  4.35839637e-01, -7.49707203e-01,
        -6.85594389e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -6.85594389e-01],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -2.01762586e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -6.07239596e-01],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -9.20658767e-01],
       [ 8.45239160e-01,  4.35839637e-01,  1.33385406e+00,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         1.76308331e-01],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
         2.21353294e+00],
       [-3.59407249e-01,  4.35839637e-01,  1.33385406e+00,
        -4.50530011e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
        -1.37110840e-01],
       [-1.56405366e+00,  4.35839637e-01, -7.49707203e-01,
         9.59856257e-01],
       [ 8.45239160e-01,  1.36165186e+00,  1.33385406e+00,
        -2.27227894e+00],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
         1.58669460e+00],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
        -5.28884803e-01],
       [ 8.45239160e-01,  6.91652519e+00, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -2.93820425e-01],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
         2.54663123e-01],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -4.50530011e-01],
       [-1.56405366e+00,  4.35839637e-01,  1.33385406e+00,
         1.90011377e+00],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -2.17433545e+00],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
        -1.07736835e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -1.37110840e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         1.35163022e+00],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -6.07239596e-01],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
        -5.28884803e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -1.37110840e-01],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -6.07239596e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
        -2.01762586e+00],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -4.31707434e-03],
       [-3.59407249e-01,  4.35839637e-01, -7.49707203e-01,
         2.15485727e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.89707407e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -5.87560474e-02],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -8.42303974e-01],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
         4.89727501e-01],
       [-3.59407249e-01,  4.35839637e-01,  1.33385406e+00,
        -2.09598066e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         4.89727501e-01],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
         2.54663123e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -2.29813602e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         3.33017916e-01],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
         1.74340418e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         8.03146672e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -9.99013559e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         2.05682335e+00],
       [-1.56405366e+00,  4.35839637e-01,  1.33385406e+00,
         1.19492064e+00],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -4.31707434e-03],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
        -5.87560474e-02],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         8.42324068e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         8.42324068e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
        -6.07239596e-01],
       [-1.56405366e+00,  1.36165186e+00, -7.49707203e-01,
         1.11656584e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -7.63949181e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -5.87560474e-02],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -5.87560474e-02],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         1.76308331e-01],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
         1.58669460e+00],
       [ 8.45239160e-01,  1.36165186e+00,  1.33385406e+00,
        -1.93927107e+00],
       [-3.59407249e-01,  4.35839637e-01, -7.49707203e-01,
         9.79535379e-02],
       [-1.56405366e+00,  4.35839637e-01, -7.49707203e-01,
         1.27327543e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         1.66504939e+00],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         2.05682335e+00],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         4.89727501e-01],
       [ 8.45239160e-01,  1.36165186e+00, -7.49707203e-01,
         5.68082294e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         2.44859732e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -1.37110840e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
        -4.50530011e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
        -6.85594389e-01],
       [ 8.45239160e-01,  2.28746408e+00,  1.33385406e+00,
        -1.70420669e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -6.07239596e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         2.01764596e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         9.79535379e-02],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -3.72175218e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         2.52695211e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         1.19492064e+00],
       [-1.56405366e+00,  4.35839637e-01, -7.49707203e-01,
         9.79535379e-02],
       [ 8.45239160e-01,  2.28746408e+00, -7.49707203e-01,
        -1.54749711e+00],
       [-1.56405366e+00,  4.35839637e-01,  1.33385406e+00,
        -2.17433545e+00],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
         4.11372708e-01],
       [ 8.45239160e-01,  4.13908852e+00, -7.49707203e-01,
        -1.46914232e+00],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
        -8.42303974e-01],
       [-1.56405366e+00,  1.36165186e+00,  1.33385406e+00,
        -9.20658767e-01],
       [-3.59407249e-01,  4.35839637e-01, -7.49707203e-01,
         1.90011377e+00],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
         2.13517815e+00],
       [ 8.45239160e-01,  6.91652519e+00, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -6.07239596e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -9.20658767e-01],
       [-1.56405366e+00,  4.35839637e-01,  1.33385406e+00,
         4.89727501e-01],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
         2.54663123e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         8.03146672e-01],
       [ 8.45239160e-01,  4.35839637e-01,  1.33385406e+00,
        -2.93820425e-01],
       [-3.59407249e-01,  4.35839637e-01, -7.49707203e-01,
         9.79535379e-02],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
         1.58669460e+00],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -4.31707434e-03],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
         4.89727501e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -6.07239596e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         2.54663123e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -5.28884803e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01,  3.21327630e+00, -7.49707203e-01,
        -2.01762586e+00],
       [ 8.45239160e-01,  3.21327630e+00, -7.49707203e-01,
        -1.78256149e+00],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         2.52695211e+00],
       [ 8.45239160e-01,  4.13908852e+00, -7.49707203e-01,
        -1.23407794e+00],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         1.03821105e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -7.63949181e-01],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -9.99013559e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -8.42303974e-01],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
         4.11372708e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01,  4.35839637e-01,  1.33385406e+00,
        -4.31707434e-03],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -9.20658767e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         2.05682335e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -2.93820425e-01],
       [-1.56405366e+00,  4.35839637e-01, -7.49707203e-01,
        -2.15465633e-01],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -9.20658767e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -6.85594389e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.50530011e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -8.42303974e-01],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
         4.11372708e-01],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -4.31707434e-03],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
         2.05682335e+00],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
         4.11372708e-01],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
        -8.42303974e-01],
       [ 8.45239160e-01,  3.21327630e+00,  1.33385406e+00,
        -1.62585190e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.50530011e-01],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -1.93927107e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -9.79334437e-02],
       [-1.56405366e+00,  4.35839637e-01, -7.49707203e-01,
         1.42998501e+00],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
         6.46437086e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -8.42303974e-01],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -2.25269024e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
        -9.20658767e-01],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
         1.58669460e+00],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -4.31707434e-03],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
        -8.42303974e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -6.85594389e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-3.59407249e-01,  4.35839637e-01,  1.33385406e+00,
         1.11656584e+00],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -4.31707434e-03],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
        -1.37110840e-01],
       [ 8.45239160e-01,  1.36165186e+00,  1.33385406e+00,
        -9.20658767e-01],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -2.15465633e-01],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
        -5.28884803e-01],
       [-1.56405366e+00,  2.28746408e+00,  1.33385406e+00,
        -4.50530011e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -6.07239596e-01],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -2.93820425e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -9.99013559e-01],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
         3.33017916e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -2.15465633e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01,  4.13908852e+00, -7.49707203e-01,
        -1.62585190e+00],
       [ 8.45239160e-01,  4.35839637e-01,  1.33385406e+00,
        -4.31707434e-03],
       [ 8.45239160e-01,  4.35839637e-01,  1.33385406e+00,
        -1.15572314e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         8.81501464e-01],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
         9.79535379e-02],
       [-1.56405366e+00,  4.35839637e-01, -7.49707203e-01,
         2.37024252e+00],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
         1.95987452e-02],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         1.76308331e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -7.63949181e-01],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -1.07736835e+00],
       [-1.56405366e+00,  4.35839637e-01,  1.33385406e+00,
         2.37024252e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         6.46437086e-01],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -2.93820425e-01],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
        -1.07736835e+00],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
         5.68082294e-01],
       [-3.59407249e-01,  4.35839637e-01,  1.33385406e+00,
        -1.37110840e-01],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
         2.54663123e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         1.76308331e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -6.07239596e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         1.35163022e+00],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         1.76308331e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -2.93820425e-01],
       [-1.56405366e+00, -4.89972585e-01,  1.33385406e+00,
         2.52695211e+00],
       [ 8.45239160e-01,  2.28746408e+00,  1.33385406e+00,
        -1.62585190e+00],
       [ 8.45239160e-01,  1.36165186e+00, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -6.07239596e-01],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
        -3.72175218e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         1.97846856e+00],
       [ 8.45239160e-01, -4.89972585e-01,  1.33385406e+00,
        -1.23407794e+00],
       [-3.59407249e-01, -4.89972585e-01,  1.33385406e+00,
        -4.31707434e-03],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -6.85594389e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
        -4.31707434e-03],
       [ 8.45239160e-01,  4.35839637e-01, -7.49707203e-01,
        -7.63949181e-01],
       [-1.56405366e+00, -4.89972585e-01, -7.49707203e-01,
         1.19492064e+00],
       [-1.56405366e+00,  4.35839637e-01,  1.33385406e+00,
        -9.99013559e-01],
       [ 8.45239160e-01, -4.89972585e-01, -7.49707203e-01,
         1.03821105e+00],
       [-3.59407249e-01, -4.89972585e-01, -7.49707203e-01,
         5.28904897e-01]])

In [52]:
x=np.ones(len(data)).reshape(-1,1)
x_train=np.concatenate((x_train,x),axis=1)
x_train.shape

(667, 5)

In [53]:
y=np.ones(len(x_test)).reshape(-1,1)
x_test=np.concatenate((x_test,y),axis=1)
x_test.shape

(223, 5)

In [54]:
data=np.concatenate((x_train,y_train.reshape(-1,1)),axis=1)
data.shape

(667, 6)

In [55]:
print(data.shape)
print(x_test.shape)

(667, 6)
(223, 5)

In [71]:
def run(data,x_test):
    num_iteration=30
    learning_rate=.001
    m=gd(data,num_iteration,learning_rate)
    y_pred=predict(x_test,m)
    np.savetxt("y_finalt3.csv",y_pred,fmt="%1.1f")

In [72]:
def gd(data,num_iteration,learning_rate):
    m=np.zeros((data.shape)[1]-1)
    for i in range(num_iteration):
        m=step_gradient(data,m,learning_rate)
        #print("cost:",cost(data,m))
    return m

In [73]:
def step_gradient(data,m,learning_rate):
    new_m=np.zeros(len(m))
    N=len(data)
    for k in range(len(m)):
        sum=0
        for i in range(N):
            x=data[i,0:(data.shape)[1]-1]
            y=data[i,(data.shape)[1]-1]
            z=exp(-((m*x).sum()))
            hx=(1/(1+z))
            sum+=(-1/N)*(y-hx)*x[k]
        new_m[k]=m[k]-(learning_rate*sum)
    return new_m

In [74]:
def cost(data,m):
    sum=0
    N=len(data)
    for i in range(N):
        x=data[i,0:(data.shape)[1]-1]
        y=data[i,(data.shape)[1]-1]
        z=exp(-((m*x).sum()))
        hx=(1/(1+z))
        sum+=(-1/N)*(y*log(hx)+(1-y)*log(1-hx))
    return sum

In [75]:
def predict(x_test,m):
    y_pred=np.zeros(len(x_test))
    for i in range(len(x_test)):
        x=data[i,0:(data.shape)[1]-1]
        z=exp(-((m*x).sum()))
        hx=(1/(1+z))
        print(hx)
    return y_pred

In [76]:
run(data,x_test)

0.3994815899798266
0.3915157160679201
0.3662555930468339
0.3984907862549242
0.4109273303487056
0.37960933880654246
0.3809709614591854
0.41762303789497546
0.40168453017780065
0.3306905326539113
0.418490240438946
0.3915157160679201
0.37591520411327733
0.39131370968272666
0.40134442582008234
0.40053874170804243
0.3877657210446794
0.3555604326207523
0.37062483446735145
0.40134442582008234
0.37062483446735145
0.39236523077819563
0.36388373120657314
0.41259826921840864
0.40134442582008234
0.39074897179112755
0.36741225304265196
0.42341212470758
0.44128262017071773
0.3955266625498166
0.3680438574054689
0.4009460425601263
0.436730740196236
0.4084526268261516
0.30299507300488904
0.3555604326207523
0.491902685862679
0.4884547266341357
0.3738489052432854
0.3915157160679201
0.39743358624285136
0.3955266625498166
0.3884108310028304
0.3618452215768134
0.41192787998257735
0.424349253487251
0.40666538010965103
0.3915157160679201
0.3916933316112626
0.30008919675674095
0.33258443658061626
0.48564333336995735
0.4357145823713617
0.3916933316112626
0.3915157160679201
0.40134442582008234
0.43110360851412177
0.3915157160679201
0.3555604326207523
0.4035356312285723
0.31967353116393377
0.3803305239646203
0.3421535035236799
0.3809709614591854
0.41086127101896985
0.40373976196621203
0.40426445490795676
0.4109273303487056
0.2914680425404375
0.34414090204060177
0.36592713985261976
0.4251516181114104
0.424349253487251
0.37798602937007364
0.28478695169960333
0.4030000408880562
0.4934295094568975
0.33966379337002367
0.37125872028830853
0.37538436488828175
0.4035356312285723
0.39104625566652307
0.4376078059079159
0.4188347091121462
0.3213496825894393
0.4109273303487056
0.36171243016925286
0.44033670110613377
0.424349253487251
0.3986267754811652
0.39498565702622285
0.3897961332841728
0.37792186820438656
0.3803305239646203
0.3877657210446794
0.4376749708366538
0.47077433211386494
0.3915157160679201
0.43449058672368734
0.4011406913954071
0.3390547622211299
0.4028819487259013
0.39671789600408053
0.43110360851412177
0.40180250753362046
0.39223275117748013
0.4209824792160814
0.3915157160679201
0.4512336428433762
0.3844953305037255
0.4583964914314625
0.3398540237624762
0.3298417246350405
0.4936414792174435
0.43333968065418
0.3885456023394168
0.38221050871886575
0.33375143135250707
0.4252202251141658
0.4523941321640549
0.4129972097633006
0.4030000408880562
0.38815651727130984
0.4285958038656419
0.39098127108253933
0.4040602386578104
0.4000246819462376
0.3915157160679201
0.3992902157008067
0.40134442582008234
0.3048604258876072
0.49407972864228733
0.3943366679617918
0.3357805902178244
0.4009460425601263
0.36069609428417404
0.40738689754839835
0.29616020092963086
0.36510047276532054
0.3287418755755175
0.37248568197606347
0.41513642809948914
0.3770842186172203
0.42772306326366183
0.4109273303487056
0.3257044603387072
0.3523430363753407
0.4007423749923136
0.37999701691350724
0.39757132327404165
0.39828753666943495
0.4357145823713617
0.3994815899798266
0.39074897179112755
0.33044248051515124
0.41192787998257735
0.3809709614591854
0.3619082412375788
0.44556746347647164
0.4015986965660821
0.29299901978588794
0.39518832828134676
0.34926302120791425
0.38358756685571876
0.43211724761963705
0.41755666516350953
0.39389098793494853
0.3915157160679201
0.4107220688097904
0.46436805165630274
0.3915157160679201
0.32679909468722523
0.4149305450242275
0.32075753839673893
0.2745027293410343
0.47765448218673473
0.3847368664066668
0.38874709238900046
0.4099987311605308
0.3768850463312689
0.2713257907033775
0.39236523077819563
0.4011406913954071
0.4031365376078703
0.37862493118011636
0.48156243037694985
0.3445741035494187
0.4218516045976871
0.4035356312285723
0.3915157160679201
0.40048828356387456
0.4379261449213623
0.40632392248825877
0.44251077741301753
0.40334060297941826
0.3915157160679201
0.40048828356387456
0.4275155008187613
0.4009460425601263
0.3915157160679201
0.3917588551245463
0.3325221291253
0.40134442582008234
0.3915157160679201
0.4248057516660023
0.43110360851412177
0.3625358063816879
0.3927027174161259
0.3736504167737266
0.4606166475430908
0.365730400655663
0.42285965943287557
0.4276562640784471
0.3915157160679201
0.48088620489397405
0.3915157160679201
0.3662555930468339
0.46780147146399625
0.3963792109435323
0.41158506883904367
0.40088049584195407
0.42772306326366183
0.3115035089994137

In [63]:
from sklearn.linear_model import LogisticRegression
alg=LogisticRegression?