In [1]:
import numpy as np
import pandas as pd 
from math import exp,log
data=pd.read_csv("x_y_train.csv")
x_test=pd.read_csv("x_test.csv")
x_train=data.iloc[:,0:(data.shape)[1]-1]
y_train=data.iloc[:,(data.shape)[1]-1]
x_train.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.0,1,0,228414,26.000,NaN,S
1,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.050,NaN,S
2,2,"Morley, Mr. Henry Samuel (""Mr Henry Marshall"")",male,39.0,0,0,250655,26.000,NaN,S
3,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,349909,21.075,NaN,S
4,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S

In [2]:
x_train.drop(['Name','Fare','Ticket','Cabin'],axis=1,inplace=True)
x_test.drop(['Name','Fare','Ticket','Cabin'],axis=1,inplace=True)
print(x_train.shape)
print(x_test.shape)

(668, 6)
(223, 6)

In [3]:
def f(s):
    if s=='C':
        return 0
    elif s=='Q':
        return 1
    elif s=='S':
        return 2
def k(s):
    if s=='male':
        return 0
    elif s=='female':
        return 1
x_train['embarked']=x_train['Embarked'].apply(f)
x_train['sex']=x_train['Sex'].apply(k)
x_test['embarked']=x_test['Embarked'].apply(f)
x_test['sex']=x_test['Sex'].apply(k)
print(x_train.shape)
print(x_test.shape)

(668, 8)
(223, 8)

In [4]:
x_train.drop(['Embarked','Sex'],axis=1,inplace=True)
x_test.drop(['Embarked','Sex'],axis=1,inplace=True)

In [5]:
print(x_train.head())
print(x_test.head())

   Pclass   Age  SibSp  Parch  embarked  sex
0       2  29.0      1      0       2.0    1
1       3   NaN      0      0       2.0    0
2       2  39.0      0      0       2.0    0
3       3  29.0      0      4       2.0    1
4       3  25.0      0      0       2.0    0
   Pclass   Age  SibSp  Parch  embarked  sex
0       2   8.0      1      1       2.0    0
1       1  49.0      0      0       2.0    1
2       3   NaN      0      0       1.0    0
3       2  24.0      2      1       2.0    1
4       1  36.0      0      0       2.0    0

In [6]:
x_train=np.array(x_train)
y_train=np.array(y_train)
data=np.concatenate((x_train,y_train.reshape(-1,1)),axis=1)
data=pd.DataFrame(data)
data.columns=['Pclass','Age','SibSp','Parch','embarked','Sex','Survived']
data

     Pclass    Age  SibSp  Parch  embarked  Sex  Survived
0       2.0  29.00    1.0    0.0       2.0  1.0       1.0
1       3.0    NaN    0.0    0.0       2.0  0.0       0.0
2       2.0  39.00    0.0    0.0       2.0  0.0       0.0
3       3.0  29.00    0.0    4.0       2.0  1.0       0.0
4       3.0  25.00    0.0    0.0       2.0  0.0       0.0
5       3.0  34.50    0.0    0.0       0.0  0.0       0.0
6       1.0  35.00    1.0    0.0       2.0  1.0       1.0
7       3.0  23.00    0.0    0.0       2.0  0.0       0.0
8       2.0    NaN    0.0    0.0       2.0  0.0       1.0
9       3.0  50.00    0.0    0.0       2.0  0.0       0.0
10      3.0  23.00    0.0    0.0       2.0  1.0       1.0
11      3.0    NaN    0.0    0.0       0.0  0.0       0.0
12      2.0  36.00    0.0    0.0       2.0  0.0       0.0
13      3.0    NaN    1.0    0.0       1.0  0.0       0.0
14      3.0    NaN    0.0    0.0       1.0  1.0       1.0
15      3.0  28.00    2.0    0.0       2.0  0.0       0.0
16      3.0  32.00    0.0    0.0       2.0  0.0       1.0
17      3.0  42.00    0.0    0.0       2.0  0.0       0.0
18      1.0  38.00    0.0    1.0       2.0  0.0       0.0
19      3.0    NaN    0.0    0.0       1.0  1.0       1.0
20      1.0  38.00    0.0    0.0       2.0  0.0       0.0
21      3.0    NaN    0.0    2.0       0.0  1.0       0.0
22      2.0  40.00    0.0    0.0       2.0  1.0       1.0
23      3.0  24.50    0.0    0.0       2.0  0.0       0.0
24      3.0    NaN    0.0    0.0       0.0  1.0       1.0
25      3.0    NaN    8.0    2.0       2.0  1.0       0.0
26      1.0  39.00    0.0    0.0       2.0  0.0       0.0
27      1.0  22.00    0.0    0.0       0.0  0.0       0.0
28      3.0  16.00    0.0    0.0       2.0  0.0       0.0
29      2.0  30.00    0.0    0.0       2.0  0.0       0.0
..      ...    ...    ...    ...       ...  ...       ...
638     3.0  24.00    2.0    0.0       2.0  0.0       0.0
639     2.0  22.00    1.0    2.0       0.0  1.0       1.0
640     3.0    NaN    3.0    1.0       2.0  1.0       0.0
641     3.0  32.00    0.0    0.0       2.0  0.0       1.0
642     1.0  42.00    0.0    0.0       2.0  0.0       1.0
643     3.0  17.00    0.0    0.0       2.0  0.0       0.0
644     1.0    NaN    0.0    0.0       2.0  0.0       0.0
645     2.0   0.83    1.0    1.0       2.0  0.0       1.0
646     3.0   9.00    2.0    2.0       2.0  1.0       0.0
647     1.0  58.00    0.0    0.0       0.0  0.0       0.0
648     2.0  28.00    0.0    1.0       2.0  0.0       0.0
649     3.0  26.00    0.0    0.0       2.0  0.0       0.0
650     3.0  47.00    0.0    0.0       2.0  0.0       0.0
651     3.0    NaN    1.0    0.0       2.0  0.0       0.0
652     2.0  33.00    1.0    2.0       2.0  1.0       1.0
653     3.0  47.00    1.0    0.0       2.0  1.0       0.0
654     3.0    NaN    0.0    0.0       2.0  0.0       0.0
655     1.0  42.00    1.0    0.0       2.0  0.0       1.0
656     3.0  36.00    0.0    0.0       2.0  0.0       0.0
657     3.0  38.00    0.0    0.0       2.0  0.0       0.0
658     3.0  38.00    1.0    5.0       2.0  1.0       1.0
659     3.0    NaN    0.0    0.0       1.0  0.0       0.0
660     2.0   1.00    2.0    1.0       2.0  0.0       1.0
661     1.0    NaN    1.0    0.0       0.0  1.0       1.0
662     1.0  47.00    0.0    0.0       2.0  0.0       0.0
663     2.0  17.00    0.0    0.0       2.0  1.0       1.0
664     3.0    NaN    0.0    0.0       1.0  0.0       0.0
665     3.0  32.00    0.0    0.0       2.0  0.0       1.0
666     3.0  22.00    0.0    0.0       2.0  1.0       0.0
667     3.0    NaN    1.0    0.0       1.0  1.0       1.0

[668 rows x 7 columns]

In [7]:
data.head()

   Pclass   Age  SibSp  Parch  embarked  Sex  Survived
0     2.0  29.0    1.0    0.0       2.0  1.0       1.0
1     3.0   NaN    0.0    0.0       2.0  0.0       0.0
2     2.0  39.0    0.0    0.0       2.0  0.0       0.0
3     3.0  29.0    0.0    4.0       2.0  1.0       0.0
4     3.0  25.0    0.0    0.0       2.0  0.0       0.0

In [8]:
means=data[data['Survived']==1]['Age'].mean()
means

28.138157894736842

In [9]:
meann=data[data['Survived']==0]['Age'].mean()
meann

30.857142857142858

In [10]:
data["age1"]=np.where(pd.isnull(data.Age) & (data["Survived"]==0),meann,data["Age"])
data.head()

   Pclass   Age  SibSp  Parch  embarked  Sex  Survived       age1
0     2.0  29.0    1.0    0.0       2.0  1.0       1.0  29.000000
1     3.0   NaN    0.0    0.0       2.0  0.0       0.0  30.857143
2     2.0  39.0    0.0    0.0       2.0  0.0       0.0  39.000000
3     3.0  29.0    0.0    4.0       2.0  1.0       0.0  29.000000
4     3.0  25.0    0.0    0.0       2.0  0.0       0.0  25.000000

In [11]:
data['age1'].fillna(means,inplace=True)

In [12]:
data.drop(['Age'],axis=1,inplace=True)

In [13]:
data.dropna(inplace=True)

In [14]:

data=np.array(data)
data=pd.DataFrame(data)
data.columns=[0,1,2,3,4,6,5]
data.sort_index(axis=1,inplace=True)
data

       0    1    2    3    4          5    6
0    2.0  1.0  0.0  2.0  1.0  29.000000  1.0
1    3.0  0.0  0.0  2.0  0.0  30.857143  0.0
2    2.0  0.0  0.0  2.0  0.0  39.000000  0.0
3    3.0  0.0  4.0  2.0  1.0  29.000000  0.0
4    3.0  0.0  0.0  2.0  0.0  25.000000  0.0
5    3.0  0.0  0.0  0.0  0.0  34.500000  0.0
6    1.0  1.0  0.0  2.0  1.0  35.000000  1.0
7    3.0  0.0  0.0  2.0  0.0  23.000000  0.0
8    2.0  0.0  0.0  2.0  0.0  28.138158  1.0
9    3.0  0.0  0.0  2.0  0.0  50.000000  0.0
10   3.0  0.0  0.0  2.0  1.0  23.000000  1.0
11   3.0  0.0  0.0  0.0  0.0  30.857143  0.0
12   2.0  0.0  0.0  2.0  0.0  36.000000  0.0
13   3.0  1.0  0.0  1.0  0.0  30.857143  0.0
14   3.0  0.0  0.0  1.0  1.0  28.138158  1.0
15   3.0  2.0  0.0  2.0  0.0  28.000000  0.0
16   3.0  0.0  0.0  2.0  0.0  32.000000  1.0
17   3.0  0.0  0.0  2.0  0.0  42.000000  0.0
18   1.0  0.0  1.0  2.0  0.0  38.000000  0.0
19   3.0  0.0  0.0  1.0  1.0  28.138158  1.0
20   1.0  0.0  0.0  2.0  0.0  38.000000  0.0
21   3.0  0.0  2.0  0.0  1.0  30.857143  0.0
22   2.0  0.0  0.0  2.0  1.0  40.000000  1.0
23   3.0  0.0  0.0  2.0  0.0  24.500000  0.0
24   3.0  0.0  0.0  0.0  1.0  28.138158  1.0
25   3.0  8.0  2.0  2.0  1.0  30.857143  0.0
26   1.0  0.0  0.0  2.0  0.0  39.000000  0.0
27   1.0  0.0  0.0  0.0  0.0  22.000000  0.0
28   3.0  0.0  0.0  2.0  0.0  16.000000  0.0
29   2.0  0.0  0.0  2.0  0.0  30.000000  0.0
..   ...  ...  ...  ...  ...        ...  ...
637  3.0  2.0  0.0  2.0  0.0  24.000000  0.0
638  2.0  1.0  2.0  0.0  1.0  22.000000  1.0
639  3.0  3.0  1.0  2.0  1.0  30.857143  0.0
640  3.0  0.0  0.0  2.0  0.0  32.000000  1.0
641  1.0  0.0  0.0  2.0  0.0  42.000000  1.0
642  3.0  0.0  0.0  2.0  0.0  17.000000  0.0
643  1.0  0.0  0.0  2.0  0.0  30.857143  0.0
644  2.0  1.0  1.0  2.0  0.0   0.830000  1.0
645  3.0  2.0  2.0  2.0  1.0   9.000000  0.0
646  1.0  0.0  0.0  0.0  0.0  58.000000  0.0
647  2.0  0.0  1.0  2.0  0.0  28.000000  0.0
648  3.0  0.0  0.0  2.0  0.0  26.000000  0.0
649  3.0  0.0  0.0  2.0  0.0  47.000000  0.0
650  3.0  1.0  0.0  2.0  0.0  30.857143  0.0
651  2.0  1.0  2.0  2.0  1.0  33.000000  1.0
652  3.0  1.0  0.0  2.0  1.0  47.000000  0.0
653  3.0  0.0  0.0  2.0  0.0  30.857143  0.0
654  1.0  1.0  0.0  2.0  0.0  42.000000  1.0
655  3.0  0.0  0.0  2.0  0.0  36.000000  0.0
656  3.0  0.0  0.0  2.0  0.0  38.000000  0.0
657  3.0  1.0  5.0  2.0  1.0  38.000000  1.0
658  3.0  0.0  0.0  1.0  0.0  30.857143  0.0
659  2.0  2.0  1.0  2.0  0.0   1.000000  1.0
660  1.0  1.0  0.0  0.0  1.0  28.138158  1.0
661  1.0  0.0  0.0  2.0  0.0  47.000000  0.0
662  2.0  0.0  0.0  2.0  1.0  17.000000  1.0
663  3.0  0.0  0.0  1.0  0.0  30.857143  0.0
664  3.0  0.0  0.0  2.0  0.0  32.000000  1.0
665  3.0  0.0  0.0  2.0  1.0  22.000000  0.0
666  3.0  1.0  0.0  1.0  1.0  28.138158  1.0

[667 rows x 7 columns]

In [15]:
data.columns=['Pclass','Sibsp','Parch','embarked','sex','age','Survived']
data

     Pclass  Sibsp  Parch  embarked  sex        age  Survived
0       2.0    1.0    0.0       2.0  1.0  29.000000       1.0
1       3.0    0.0    0.0       2.0  0.0  30.857143       0.0
2       2.0    0.0    0.0       2.0  0.0  39.000000       0.0
3       3.0    0.0    4.0       2.0  1.0  29.000000       0.0
4       3.0    0.0    0.0       2.0  0.0  25.000000       0.0
5       3.0    0.0    0.0       0.0  0.0  34.500000       0.0
6       1.0    1.0    0.0       2.0  1.0  35.000000       1.0
7       3.0    0.0    0.0       2.0  0.0  23.000000       0.0
8       2.0    0.0    0.0       2.0  0.0  28.138158       1.0
9       3.0    0.0    0.0       2.0  0.0  50.000000       0.0
10      3.0    0.0    0.0       2.0  1.0  23.000000       1.0
11      3.0    0.0    0.0       0.0  0.0  30.857143       0.0
12      2.0    0.0    0.0       2.0  0.0  36.000000       0.0
13      3.0    1.0    0.0       1.0  0.0  30.857143       0.0
14      3.0    0.0    0.0       1.0  1.0  28.138158       1.0
15      3.0    2.0    0.0       2.0  0.0  28.000000       0.0
16      3.0    0.0    0.0       2.0  0.0  32.000000       1.0
17      3.0    0.0    0.0       2.0  0.0  42.000000       0.0
18      1.0    0.0    1.0       2.0  0.0  38.000000       0.0
19      3.0    0.0    0.0       1.0  1.0  28.138158       1.0
20      1.0    0.0    0.0       2.0  0.0  38.000000       0.0
21      3.0    0.0    2.0       0.0  1.0  30.857143       0.0
22      2.0    0.0    0.0       2.0  1.0  40.000000       1.0
23      3.0    0.0    0.0       2.0  0.0  24.500000       0.0
24      3.0    0.0    0.0       0.0  1.0  28.138158       1.0
25      3.0    8.0    2.0       2.0  1.0  30.857143       0.0
26      1.0    0.0    0.0       2.0  0.0  39.000000       0.0
27      1.0    0.0    0.0       0.0  0.0  22.000000       0.0
28      3.0    0.0    0.0       2.0  0.0  16.000000       0.0
29      2.0    0.0    0.0       2.0  0.0  30.000000       0.0
..      ...    ...    ...       ...  ...        ...       ...
637     3.0    2.0    0.0       2.0  0.0  24.000000       0.0
638     2.0    1.0    2.0       0.0  1.0  22.000000       1.0
639     3.0    3.0    1.0       2.0  1.0  30.857143       0.0
640     3.0    0.0    0.0       2.0  0.0  32.000000       1.0
641     1.0    0.0    0.0       2.0  0.0  42.000000       1.0
642     3.0    0.0    0.0       2.0  0.0  17.000000       0.0
643     1.0    0.0    0.0       2.0  0.0  30.857143       0.0
644     2.0    1.0    1.0       2.0  0.0   0.830000       1.0
645     3.0    2.0    2.0       2.0  1.0   9.000000       0.0
646     1.0    0.0    0.0       0.0  0.0  58.000000       0.0
647     2.0    0.0    1.0       2.0  0.0  28.000000       0.0
648     3.0    0.0    0.0       2.0  0.0  26.000000       0.0
649     3.0    0.0    0.0       2.0  0.0  47.000000       0.0
650     3.0    1.0    0.0       2.0  0.0  30.857143       0.0
651     2.0    1.0    2.0       2.0  1.0  33.000000       1.0
652     3.0    1.0    0.0       2.0  1.0  47.000000       0.0
653     3.0    0.0    0.0       2.0  0.0  30.857143       0.0
654     1.0    1.0    0.0       2.0  0.0  42.000000       1.0
655     3.0    0.0    0.0       2.0  0.0  36.000000       0.0
656     3.0    0.0    0.0       2.0  0.0  38.000000       0.0
657     3.0    1.0    5.0       2.0  1.0  38.000000       1.0
658     3.0    0.0    0.0       1.0  0.0  30.857143       0.0
659     2.0    2.0    1.0       2.0  0.0   1.000000       1.0
660     1.0    1.0    0.0       0.0  1.0  28.138158       1.0
661     1.0    0.0    0.0       2.0  0.0  47.000000       0.0
662     2.0    0.0    0.0       2.0  1.0  17.000000       1.0
663     3.0    0.0    0.0       1.0  0.0  30.857143       0.0
664     3.0    0.0    0.0       2.0  0.0  32.000000       1.0
665     3.0    0.0    0.0       2.0  1.0  22.000000       0.0
666     3.0    1.0    0.0       1.0  1.0  28.138158       1.0

[667 rows x 7 columns]

In [16]:
mean=x_test['Age'].mean()
mean

29.694775280898877

In [17]:
x_test['age']=np.where(pd.isnull(x_test.Age),mean,x_test['Age'])
x_test.drop(['Age'],axis=1,inplace=True)
x_test

     Pclass  SibSp  Parch  embarked  sex        age
0         2      1      1       2.0    0   8.000000
1         1      0      0       2.0    1  49.000000
2         3      0      0       1.0    0  29.694775
3         2      2      1       2.0    1  24.000000
4         1      0      0       2.0    0  36.000000
5         1      0      0       0.0    0  71.000000
6         3      0      0       2.0    0  16.000000
7         3      0      0       1.0    0  29.694775
8         3      0      0       2.0    1  18.000000
9         3      0      0       2.0    0  29.694775
10        1      1      0       2.0    1  63.000000
11        3      0      0       2.0    0  29.694775
12        1      0      0       0.0    1  24.000000
13        3      0      0       2.0    1  23.000000
14        1      0      0       0.0    0  71.000000
15        2      1      0       2.0    0  21.000000
16        3      0      0       2.0    0  21.000000
17        3      1      1       2.0    0   4.000000
18        3      0      0       2.0    0  22.000000
19        3      0      0       1.0    1  18.000000
20        3      1      0       1.0    1  29.694775
21        3      0      0       1.0    0  32.000000
22        1      0      0       2.0    1  58.000000
23        2      1      2       2.0    1  24.000000
24        3      0      0       2.0    0  29.694775
25        1      0      0       2.0    0  29.694775
26        2      0      0       2.0    0  28.000000
27        1      1      0       2.0    0  42.000000
28        3      2      1       0.0    1   0.750000
29        2      0      0       2.0    1  50.000000
..      ...    ...    ...       ...  ...        ...
193       3      0      0       2.0    0  29.694775
194       3      0      0       2.0    0  38.000000
195       3      0      0       2.0    1  26.000000
196       1      0      1       0.0    1  16.000000
197       3      0      0       2.0    1  37.000000
198       2      1      0       2.0    1  28.000000
199       1      0      0       2.0    1  33.000000
200       3      0      0       1.0    0  29.694775
201       1      0      0       0.0    0  32.000000
202       3      0      0       2.0    0  22.000000
203       1      0      0       2.0    0  47.000000
204       3      0      0       1.0    0  29.694775
205       3      1      0       2.0    0  29.694775
206       3      0      0       2.0    0  32.000000
207       3      0      0       2.0    0  26.000000
208       1      0      0       NaN    1  62.000000
209       3      3      2       2.0    1   9.000000
210       3      2      0       0.0    0  29.694775
211       3      0      0       2.0    1  22.000000
212       2      0      0       2.0    0  25.000000
213       1      0      0       2.0    0  55.000000
214       3      0      0       2.0    1  14.000000
215       2      0      0       1.0    1  29.694775
216       3      0      0       2.0    0  21.000000
217       3      0      0       2.0    0  29.694775
218       3      1      0       2.0    0  20.000000
219       1      0      0       2.0    0  45.000000
220       1      1      0       0.0    1  17.000000
221       3      0      0       2.0    0  43.000000
222       2      0      2       2.0    0  36.500000

[223 rows x 6 columns]

In [18]:
x_test.describe()
x_test.dropna(inplace=True)
x_test.describe()

           Pclass       SibSp       Parch    embarked         sex         age
count  222.000000  222.000000  222.000000  222.000000  222.000000  222.000000
mean     2.351351    0.509009    0.306306    1.563063    0.324324   29.549256
std      0.847126    1.171845    0.635208    0.750918    0.469180   13.607021
min      1.000000    0.000000    0.000000    0.000000    0.000000    0.420000
25%      2.000000    0.000000    0.000000    1.000000    0.000000   22.000000
50%      3.000000    0.000000    0.000000    2.000000    0.000000   29.694775
75%      3.000000    1.000000    0.000000    2.000000    1.000000   35.000000
max      3.000000    8.000000    2.000000    2.000000    1.000000   71.000000

In [19]:
data=np.array(data)
x_test=np.array(x_test)

In [20]:
x_train=data[:,0:(data.shape)[1]-1]
y_train=data[:,(data.shape)[1]-1]

In [21]:
from sklearn import preprocessing
scaler=preprocessing.StandardScaler()
scaler.fit(x_train)
scaler.transform(x_train)
scaler.transform(x_test)

array([[-0.35940725,  0.43583964,  0.69300165,  0.58848601, -0.7497072 ,
        -1.70420669],
       [-1.56405366, -0.48997259, -0.4772062 ,  0.58848601,  1.33385406,
         1.50833981],
       [ 0.84523916, -0.48997259, -0.4772062 , -0.65366642, -0.7497072 ,
        -0.00431707],
       ...,
       [-1.56405366,  0.43583964, -0.4772062 , -1.89581885,  1.33385406,
        -0.99901356],
       [ 0.84523916, -0.48997259, -0.4772062 ,  0.58848601, -0.7497072 ,
         1.03821105],
       [-0.35940725, -0.48997259,  1.86320951,  0.58848601, -0.7497072 ,
         0.5289049 ]])

In [22]:
x=np.ones(len(data)).reshape(-1,1)
x_train=np.concatenate((x_train,x),axis=1)
x_train.shape

(667, 7)

In [23]:
y=np.ones(len(x_test)).reshape(-1,1)
x_test=np.concatenate((x_test,y),axis=1)
x_test.shape

(222, 7)

In [24]:
data=np.concatenate((x_train,y_train.reshape(-1,1)),axis=1)
data.shape

(667, 8)

In [25]:
print(data.shape)
print(x_test.shape)

(667, 8)
(222, 7)

In [26]:
def run(data,x_test):
    num_iteration=3000
    learning_rate=.001
    m=gd(data,num_iteration,learning_rate)
    y_pred=predict(x_test,m)
    np.savetxt("y_finalt2.csv",y_pred,fmt="%1.1f")

In [27]:
def gd(data,num_iteration,learning_rate):
    m=np.zeros((data.shape)[1]-1)
    for i in range(num_iteration):
        m=step_gradient(data,m,learning_rate)
        print("cost:",cost(data,m))
    return m

In [28]:
def step_gradient(data,m,learning_rate):
    new_m=np.zeros(len(m))
    N=len(data)
    for k in range(len(m)):
        sum=0
        for i in range(N):
            x=data[i,0:(data.shape)[1]-1]
            y=data[i,(data.shape)[1]-1]
            z=exp(-((m*x).sum()))
            hx=(1/(1+z))
            sum+=(-1/N)*(y-hx)*x[k]
        new_m[k]=m[k]-(learning_rate*sum)
    return new_m

In [ ]:
def cost(data,m):
    sum=0
    N=len(data)
    for i in range(N):
        x=data[i,0:(data.shape)[1]-1]
        y=data[i,(data.shape)[1]-1]
        z=exp(-((m*x).sum()))
        hx=(1/(1+z))
        sum+=(-1/N)*(y*log(hx)+(1-y)*log(1-hx))
    return sum

In [ ]:
def predict(x_test,m):
    y_pred=np.zeros(len(x_test))
    for i in range(len(x_test)):
        x=data[i,0:(data.shape)[1]-1]
        z=exp(-((m*x).sum()))
        hx=(1/(1+z))
        if hx<0.5:
            y_pred[i]=0
        else:
            y_pred[i]=1
    return y_pred

In [ ]:
run(data,x_test)

cost: 0.6818168022319723
cost: 0.6756421851841032
cost: 0.672245914140877
cost: 0.6703544216053876
cost: 0.6692852444064016
cost: 0.6686696230521386
cost: 0.6683062399858523
cost: 0.6680841051658579
cost: 0.6679415075706657
cost: 0.6678438963857138
cost: 0.6677718197365461
cost: 0.667714278614089
cost: 0.6676650326337485
cost: 0.667620532044048
cost: 0.6675787535956759
cost: 0.6675385423438
cost: 0.667499238238837
cost: 0.6674604637292479
cost: 0.6674220027067217
cost: 0.6673837314061001
cost: 0.667345578916093
cost: 0.6673075045921226
cost: 0.6672694851282521
cost: 0.6672315071539684
cost: 0.6671935629931394
cost: 0.6671556482337956
cost: 0.6671177603352744
cost: 0.6670798978297966
cost: 0.6670420598647384
cost: 0.6670042459401945
cost: 0.666966455758518
cost: 0.6669286891380397
cost: 0.6668909459636014
cost: 0.6668532261581921
cost: 0.6668155296666833
cost: 0.6667778564465018
cost: 0.6667402064622888
cost: 0.6667025796828308
cost: 0.6666649760792996
cost: 0.6666273956242558
cost: 0.6665898382910586
cost: 0.6665523040535453
cost: 0.6665147928858363
cost: 0.6664773047622278
cost: 0.6664398396571303
cost: 0.6664023975450303
cost: 0.6663649784004761
cost: 0.666327582198054
cost: 0.6662902089124032
cost: 0.6662528585181863
cost: 0.6662155309901042
cost: 0.6661782263028899
cost: 0.6661409444313086
cost: 0.6661036853501536
cost: 0.6660664490342528
cost: 0.6660292354584646
cost: 0.665992044597672
cost: 0.6659548764267952
cost: 0.665917730920785
cost: 0.665880608054615
cost: 0.6658435078032977
cost: 0.6658064301418718
cost: 0.6657693750454093
cost: 0.6657323424890063
cost: 0.6656953324477953
cost: 0.6656583448969373
cost: 0.6656213798116214
cost: 0.6655844371670688
cost: 0.665547516938532
cost: 0.6655106191012898
cost: 0.665473743630655
cost: 0.6654368905019672
cost: 0.6654000596905981
cost: 0.6653632511719494
cost: 0.6653264649214524
cost: 0.6652897009145632
cost: 0.6652529591267785
cost: 0.665216239533617
cost: 0.6651795421106286
cost: 0.6651428668333909
cost: 0.6651062136775162
cost: 0.6650695826186439
cost: 0.6650329736324427
cost: 0.6649963866946098
cost: 0.6649598217808751
cost: 0.6649232788669969
cost: 0.6648867579287603
cost: 0.6648502589419862
cost: 0.6648137818825155
cost: 0.6647773267262278
cost: 0.6647408934490272
cost: 0.6647044820268478
cost: 0.6646680924356552
cost: 0.6646317246514394
cost: 0.6645953786502243
cost: 0.6645590544080617
cost: 0.6645227519010319
cost: 0.664486471105246
cost: 0.6644502119968425
cost: 0.6644139745519891
cost: 0.6643777587468847
cost: 0.6643415645577531
cost: 0.6643053919608498
cost: 0.6642692409324622
cost: 0.6642331114489025
cost: 0.6641970034865101
cost: 0.6641609170216586
cost: 0.6641248520307467
cost: 0.6640888084902038
cost: 0.6640527863764877
cost: 0.6640167856660839
cost: 0.6639808063355064
cost: 0.6639448483613015
cost: 0.6639089117200405
cost: 0.6638729963883228
cost: 0.6638371023427806
cost: 0.6638012295600676
cost: 0.6637653780168756
cost: 0.6637295476899158
cost: 0.6636937385559342
cost: 0.6636579505917004
cost: 0.6636221837740182
cost: 0.6635864380797142
cost: 0.6635507134856448
cost: 0.6635150099686972
cost: 0.6634793275057818
cost: 0.6634436660738446
cost: 0.6634080256498543
cost: 0.6633724062108092
cost: 0.6633368077337352
cost: 0.6633012301956878
cost: 0.6632656735737481
cost: 0.6632301378450283
cost: 0.6631946229866654
cost: 0.6631591289758285
cost: 0.6631236557897116
cost: 0.6630882034055362
cost: 0.6630527718005519
cost: 0.6630173609520412
cost: 0.6629819708373061
cost: 0.6629466014336819
cost: 0.6629112527185316
cost: 0.6628759246692428
cost: 0.6628406172632345
cost: 0.6628053304779503
cost: 0.6627700642908637
cost: 0.662734818679473
cost: 0.6626995936213097
cost: 0.6626643890939241
cost: 0.6626292050749024
cost: 0.6625940415418536
cost: 0.6625588984724168
cost: 0.662523775844255
cost: 0.6624886736350625
cost: 0.6624535918225584
cost: 0.6624185303844917
cost: 0.6623834892986359
cost: 0.6623484685427902
cost: 0.6623134680947858
cost: 0.6622784879324802
cost: 0.6622435280337564
cost: 0.6622085883765239
cost: 0.6621736689387199
cost: 0.6621387696983111
cost: 0.6621038906332881
cost: 0.6620690317216713
cost: 0.6620341929415052
cost: 0.6619993742708621
cost: 0.6619645756878428
cost: 0.6619297971705737
cost: 0.6618950386972091
cost: 0.6618603002459282
cost: 0.6618255817949382
cost: 0.661790883322476
cost: 0.6617562048067964
cost: 0.6617215462261915
cost: 0.6616869075589751
cost: 0.661652288783487
cost: 0.6616176898780936
cost: 0.6615831108211918
cost: 0.6615485515912002
cost: 0.6615140121665665
cost: 0.6614794925257624
cost: 0.6614449926472905
cost: 0.6614105125096766
cost: 0.6613760520914724
cost: 0.6613416113712589
cost: 0.6613071903276412
cost: 0.6612727889392513
cost: 0.6612384071847462
cost: 0.6612040450428133
cost: 0.661169702492161
cost: 0.6611353795115268
cost: 0.6611010760796736
cost: 0.6610667921753909
cost: 0.6610325277774965
cost: 0.660998282864828
cost: 0.6609640574162535
cost: 0.6609298514106707
cost: 0.6608956648269942
cost: 0.6608614976441709
cost: 0.6608273498411742
cost: 0.6607932213969987
cost: 0.6607591122906693
cost: 0.6607250225012341
cost: 0.6606909520077707
cost: 0.6606569007893738
cost: 0.6606228688251764
cost: 0.6605888560943262
cost: 0.6605548625760037
cost: 0.6605208882494089
cost: 0.6604869330937753
cost: 0.6604529970883543
cost: 0.660419080212429
cost: 0.6603851824453009
cost: 0.6603513037663055
cost: 0.6603174441547971
cost: 0.6602836035901604
cost: 0.6602497820517991
cost: 0.6602159795191506
cost: 0.6601821959716703
cost: 0.6601484313888434
cost: 0.6601146857501794
cost: 0.6600809590352115
cost: 0.6600472512234994
cost: 0.6600135622946285
cost: 0.6599798922282094
cost: 0.659946241003875
cost: 0.659912608601288
cost: 0.659878995000132
cost: 0.6598454001801193
cost: 0.6598118241209845
cost: 0.6597782668024871
cost: 0.6597447282044131
cost: 0.659711208306575
cost: 0.6596777070888052
cost: 0.6596442245309675
cost: 0.6596107606129423
cost: 0.6595773153146441
cost: 0.659543888616005
cost: 0.6595104804969857
cost: 0.6594770909375691
cost: 0.659443719917767
cost: 0.6594103674176112
cost: 0.6593770334171597
cost: 0.6593437178964976
cost: 0.6593104208357291
cost: 0.6592771422149902
cost: 0.6592438820144358
cost: 0.6592106402142459
cost: 0.6591774167946293
cost: 0.6591442117358148
cost: 0.6591110250180569
cost: 0.6590778566216347
cost: 0.6590447065268505
cost: 0.6590115747140333
cost: 0.6589784611635379
cost: 0.6589453658557365
cost: 0.6589122887710318
cost: 0.6588792298898468
cost: 0.6588461891926328
cost: 0.658813166659861
cost: 0.6587801622720315
cost: 0.6587471760096651
cost: 0.6587142078533074
cost: 0.6586812577835258
cost: 0.6586483257809156
cost: 0.6586154118260942
cost: 0.6585825158997064
cost: 0.6585496379824134
cost: 0.6585167780549068
cost: 0.6584839360978996
cost: 0.6584511120921295
cost: 0.6584183060183587
cost: 0.6583855178573702
cost: 0.6583527475899728
cost: 0.6583199951970009
cost: 0.6582872606593088
cost: 0.6582545439577779
cost: 0.6582218450733103
cost: 0.658189163986835
cost: 0.6581565006793032
cost: 0.658123855131687
cost: 0.6580912273249825
cost: 0.6580586172402181
cost: 0.6580260248584329
cost: 0.6579934501606969
cost: 0.6579608931281031
cost: 0.6579283537417656
cost: 0.6578958319828243
cost: 0.6578633278324401
cost: 0.6578308412717978
cost: 0.6577983722821084
cost: 0.6577659208446018
cost: 0.6577334869405345
cost: 0.6577010705511842
cost: 0.6576686716578536
cost: 0.6576362902418655
cost: 0.6576039262845687
cost: 0.6575715797673342
cost: 0.6575392506715583
cost: 0.6575069389786558
cost: 0.6574746446700656
cost: 0.6574423677272534
cost: 0.6574101081317065
cost: 0.657377865864931
cost: 0.6573456409084605
cost: 0.6573134332438482
cost: 0.657281242852675
cost: 0.6572490697165397
cost: 0.6572169138170644
cost: 0.6571847751358976
cost: 0.657152653654707
cost: 0.6571205493551843
cost: 0.6570884622190465
cost: 0.657056392228027
cost: 0.6570243393638868
cost: 0.6569923036084085
cost: 0.6569602849433969
cost: 0.6569282833506795
cost: 0.6568962988121063
cost: 0.656864331309548
cost: 0.6568323808249031
cost: 0.6568004473400865
cost: 0.6567685308370397
cost: 0.6567366312977244
cost: 0.6567047487041242
cost: 0.6566728830382467
cost: 0.6566410342821217
cost: 0.6566092024178001
cost: 0.6565773874273569
cost: 0.6565455892928881

cost: 0.6565138079965105
cost: 0.6564820435203657
cost: 0.6564502958466174
cost: 0.6564185649574473
cost: 0.6563868508350642
cost: 0.656355153461699
cost: 0.6563234728196007
cost: 0.656291808891042
cost: 0.6562601616583202
cost: 0.6562285311037495
cost: 0.6561969172096694
cost: 0.6561653199584424
cost: 0.6561337393324497
cost: 0.6561021753140983
cost: 0.6560706278858114
cost: 0.6560390970300396
cost: 0.6560075827292535
cost: 0.6559760849659426
cost: 0.6559446037226231
cost: 0.6559131389818278
cost: 0.6558816907261164
cost: 0.6558502589380656
cost: 0.6558188436002764
cost: 0.6557874446953696
cost: 0.6557560622059919
cost: 0.6557246961148042
cost: 0.655693346404496
cost: 0.6556620130577737
cost: 0.655630696057369
cost: 0.6555993953860293
cost: 0.6555681110265291
cost: 0.6555368429616636
cost: 0.6555055911742463
cost: 0.6554743556471119
cost: 0.6554431363631218
cost: 0.655411933305155
cost: 0.655380746456107
cost: 0.6553495757989052
cost: 0.655318421316489
cost: 0.655287282991824
cost: 0.655256160807895
cost: 0.6552250547477092
cost: 0.6551939647942924
cost: 0.6551628909306918
cost: 0.655131833139981
cost: 0.6551007914052479
cost: 0.6550697657096054
cost: 0.6550387560361854
cost: 0.65500776236814
cost: 0.654976784688647
cost: 0.6549458229809008
cost: 0.6549148772281151
cost: 0.6548839474135302
cost: 0.6548530335204017
cost: 0.6548221355320105
cost: 0.6547912534316547
cost: 0.6547603872026553
cost: 0.654729536828352
cost: 0.6546987022921087
cost: 0.6546678835773071
cost: 0.654637080667349
cost: 0.6546062935456595
cost: 0.654575522195683
cost: 0.6545447666008827
cost: 0.6545140267447461
cost: 0.654483302610778
cost: 0.6544525941825055
cost: 0.6544219014434735
cost: 0.6543912243772525
cost: 0.6543605629674294
cost: 0.6543299171976105
cost: 0.6542992870514265
cost: 0.654268672512526
cost: 0.6542380735645764
cost: 0.6542074901912702
cost: 0.6541769223763155
cost: 0.6541463701034432
cost: 0.6541158333564026
cost: 0.6540853121189645
cost: 0.6540548063749203
cost: 0.6540243161080821
cost: 0.6539938413022768
cost: 0.6539633819413596
cost: 0.6539329380091996
cost: 0.6539025094896899
cost: 0.6538720963667378
cost: 0.65384169862428
cost: 0.6538113162462637
cost: 0.6537809492166615
cost: 0.6537505975194648
cost: 0.653720261138683
cost: 0.6536899400583499
cost: 0.6536596342625148
cost: 0.6536293437352473
cost: 0.653599068460639
cost: 0.653568808422799
cost: 0.6535385636058592
cost: 0.6535083339939683
cost: 0.6534781195712961
cost: 0.65344792032203
cost: 0.6534177362303822
cost: 0.6533875672805769
cost: 0.6533574134568657
cost: 0.653327274743512
cost: 0.6532971511248088
cost: 0.6532670425850589
cost: 0.6532369491085884
cost: 0.653206870679745
cost: 0.6531768072828924
cost: 0.6531467589024179
cost: 0.6531167255227216
cost: 0.6530867071282299
cost: 0.6530567037033839
cost: 0.6530267152326467
cost: 0.6529967417005014
cost: 0.6529667830914448
cost: 0.6529368393899999
cost: 0.6529069105807058
cost: 0.6528769966481222
cost: 0.6528470975768239
cost: 0.6528172133514092
cost: 0.6527873439564957
cost: 0.6527574893767181
cost: 0.6527276495967291
cost: 0.6526978246012038
cost: 0.652668014374835
cost: 0.6526382189023328
cost: 0.6526084381684293
cost: 0.6525786721578727
cost: 0.6525489208554318
cost: 0.652519184245895
cost: 0.6524894623140688
cost: 0.6524597550447789
cost: 0.6524300624228677
cost: 0.6524003844331999
cost: 0.652370721060658
cost: 0.6523410722901396
cost: 0.6523114381065669
cost: 0.652281818494877
cost: 0.652252213440029
cost: 0.6522226229269962
cost: 0.6521930469407718
cost: 0.6521634854663739
cost: 0.6521339384888298
cost: 0.652104405993191
cost: 0.6520748879645266
cost: 0.6520453843879249
cost: 0.6520158952484901
cost: 0.6519864205313487
cost: 0.6519569602216424
cost: 0.6519275143045339
cost: 0.6518980827652019
cost: 0.6518686655888473
cost: 0.6518392627606842
cost: 0.6518098742659496
cost: 0.6517805000898957
cost: 0.6517511402177966
cost: 0.6517217946349417
cost: 0.651692463326637
cost: 0.6516631462782149
cost: 0.6516338434750147
cost: 0.6516045549024029
cost: 0.6515752805457606
cost: 0.6515460203904887
cost: 0.6515167744220013
cost: 0.6514875426257403
cost: 0.6514583249871552
cost: 0.6514291214917197
cost: 0.6513999321249244
cost: 0.6513707568722783
cost: 0.6513415957193059
cost: 0.6513124486515531
cost: 0.651283315654583
cost: 0.6512541967139744
cost: 0.6512250918153252
cost: 0.6511960009442542
cost: 0.6511669240863933
cost: 0.6511378612273951
cost: 0.6511088123529302
cost: 0.6510797774486856
cost: 0.6510507565003666
cost: 0.6510217494936963
cost: 0.6509927564144168
cost: 0.6509637772482842
cost: 0.6509348119810773
cost: 0.6509058605985902
cost: 0.6508769230866358
cost: 0.6508479994310407
cost: 0.6508190896176534
cost: 0.6507901936323379
cost: 0.6507613114609774
cost: 0.6507324430894732
cost: 0.6507035885037387
cost: 0.6506747476897132
cost: 0.6506459206333458
cost: 0.6506171073206063
cost: 0.6505883077374851
cost: 0.650559521869984
cost: 0.6505307497041274
cost: 0.6505019912259521
cost: 0.6504732464215177
cost: 0.6504445152768958
cost: 0.6504157977781809
cost: 0.6503870939114799
cost: 0.6503584036629195
cost: 0.6503297270186432
cost: 0.650301063964811
cost: 0.6502724144876004
cost: 0.6502437785732081
cost: 0.6502151562078455
cost: 0.6501865473777413
cost: 0.6501579520691438
cost: 0.6501293702683135
cost: 0.6501008019615327
cost: 0.6500722471350989
cost: 0.6500437057753278
cost: 0.6500151778685501
cost: 0.6499866634011161
cost: 0.649958162359388
cost: 0.6499296747297517
cost: 0.6499012004986068
cost: 0.6498727396523661
cost: 0.649844292177468
cost: 0.6498158580603584
cost: 0.6497874372875092
cost: 0.6497590298454015
cost: 0.6497306357205348
cost: 0.6497022548994279
cost: 0.6496738873686161
cost: 0.6496455331146495
cost: 0.649617192124097
cost: 0.6495888643835404
cost: 0.6495605498795827
cost: 0.6495322485988418
cost: 0.649503960527951
cost: 0.6494756856535635
cost: 0.6494474239623442
cost: 0.6494191754409779
cost: 0.6493909400761685
cost: 0.6493627178546292
cost: 0.6493345087630951
cost: 0.6493063127883174
cost: 0.6492781299170631
cost: 0.649249960136114
cost: 0.649221803432271
cost: 0.6491936597923484
cost: 0.649165529203179
cost: 0.6491374116516143
cost: 0.6491093071245166
cost: 0.6490812156087685
cost: 0.649053137091267
cost: 0.6490250715589256
cost: 0.6489970189986778
cost: 0.6489689793974668
cost: 0.6489409527422557
cost: 0.6489129390200251
cost: 0.6488849382177702
cost: 0.6488569503225006
cost: 0.6488289753212421
cost: 0.6488010132010439
cost: 0.6487730639489613
cost: 0.6487451275520718
cost: 0.648717203997466
cost: 0.6486892932722528
cost: 0.6486613953635547
cost: 0.6486335102585136
cost: 0.6486056379442833
cost: 0.648577778408035
cost: 0.6485499316369602
cost: 0.6485220976182595
cost: 0.6484942763391522
cost: 0.6484664677868742
cost: 0.6484386719486783
cost: 0.6484108888118312
cost: 0.6483831183636123
cost: 0.648355360591325
cost: 0.6483276154822815
cost: 0.648299883023812
cost: 0.6482721632032619
cost: 0.648244456007995
cost: 0.6482167614253863
cost: 0.6481890794428309
cost: 0.6481614100477352
cost: 0.6481337532275255
cost: 0.6481061089696418
cost: 0.6480784772615386
cost: 0.6480508580906873
cost: 0.6480232514445754
cost: 0.6479956573107033
cost: 0.6479680756765892
cost: 0.647940506529768
cost: 0.6479129498577878
cost: 0.6478854056482112
cost: 0.6478578738886195
cost: 0.6478303545666066
cost: 0.6478028476697845
cost: 0.6477753531857766
cost: 0.6477478711022266
cost: 0.6477204014067895
cost: 0.6476929440871371
cost: 0.6476654991309574
cost: 0.6476380665259514
cost: 0.6476106462598379
cost: 0.6475832383203487
cost: 0.6475558426952347
cost: 0.6475284593722545
cost: 0.6475010883391924
cost: 0.647473729583836
cost: 0.647446383094001
cost: 0.647419048857504
cost: 0.6473917268621903
cost: 0.6473644170959101
cost: 0.6473371195465328
cost: 0.647309834201946
cost: 0.6472825610500463
cost: 0.6472553000787477
cost: 0.6472280512759804
cost: 0.6472008146296881
cost: 0.6471735901278312
cost: 0.6471463777583848
cost: 0.6471191775093332
cost: 0.6470919893686856
cost: 0.6470648133244582
cost: 0.6470376493646858
cost: 0.6470104974774165
cost: 0.6469833576507137
cost: 0.6469562298726551
cost: 0.6469291141313347
cost: 0.6469020104148601
cost: 0.6468749187113523

cost: 0.6468478390089495
cost: 0.6468207712958045
cost: 0.6467937155600822
cost: 0.6467666717899668
cost: 0.6467396399736508
cost: 0.6467126200993467
cost: 0.646685612155279
cost: 0.6466586161296867
cost: 0.6466316320108269
cost: 0.6466046597869649